/**
 * ClawVault Commands
 * Command palette registrations
 *
 * Plugin focuses on vault health monitoring + quick capture.
 */

import { Notice } from "obsidian";
import type ClawVaultPlugin from "./main";
import { COMMAND_IDS, STATUS_VIEW_TYPE } from "./constants";
import { CaptureModal } from "./modals";

/**
 * Register all ClawVault commands
 */
export function registerCommands(plugin: ClawVaultPlugin): void {
	// Quick Capture command
	plugin.addCommand({
		id: COMMAND_IDS.QUICK_CAPTURE,
		name: "Quick capture",
		callback: () => {
			new CaptureModal(plugin.app).open();
		},
	});

	// Open Status Panel command
	plugin.addCommand({
		id: COMMAND_IDS.OPEN_STATUS_PANEL,
		name: "Open status panel",
		callback: () => {
			void activateStatusView(plugin);
		},
	});

	// Open Kanban Board command
	plugin.addCommand({
		id: COMMAND_IDS.OPEN_KANBAN_BOARD,
		name: "Open kanban board",
		callback: () => {
			void plugin.app.workspace.openLinkText("Board.md", "", "tab");
		},
	});

	// Force Refresh Stats command
	plugin.addCommand({
		id: COMMAND_IDS.REFRESH_STATS,
		name: "Refresh stats",
		callback: () => {
			void plugin.refreshAll();
		},
	});

	// Setup Graph Colors command
	plugin.addCommand({
		id: COMMAND_IDS.SETUP_GRAPH_COLORS,
		name: "Setup graph colors (neural style)",
		callback: () => {
			void setupGraphColors(plugin);
		},
	});
}

/**
 * Activate the status view in the right sidebar
 */
async function activateStatusView(plugin: ClawVaultPlugin): Promise<void> {
	const { workspace } = plugin.app;
	let leaf = workspace.getLeavesOfType(STATUS_VIEW_TYPE)[0];

	if (!leaf) {
		const rightLeaf = workspace.getRightLeaf(false);
		if (rightLeaf) {
			await rightLeaf.setViewState({
				type: STATUS_VIEW_TYPE,
				active: true,
			});
			leaf = rightLeaf;
		}
	}

	if (leaf) {
		await workspace.revealLeaf(leaf);
	}
}

/**
 * Setup neural-style graph colors
 */
async function setupGraphColors(plugin: ClawVaultPlugin): Promise<void> {
	try {
		const adapter = plugin.app.vault.adapter;

		// 1. Write the CSS snippet
		const configDir = plugin.app.vault.configDir;
		const snippetPath = `${configDir}/snippets/clawvault-graph.css`;
		const snippetCSS = `/* ClawVault Graph Colors — Neural Style */
/* Auto-generated by ClawVault plugin. Dark bg, colored nodes, green links. */

.graph-view.color-fill {
  color: #0a0e17;
}
.graph-view.color-line {
  color: #1a3d2a;
}
.graph-view.color-text {
  color: #8892a0;
}
.graph-view.color-fill-highlight {
  color: #e8a430;
}
.graph-view.color-line-highlight {
  color: #2a7d4a;
}`;

		const snippetDir = `${configDir}/snippets`;
		if (!(await adapter.exists(snippetDir))) {
			await adapter.mkdir(snippetDir);
		}
		await adapter.write(snippetPath, snippetCSS);

		// 2. Update graph.json with colorGroups
		const config = await plugin.vaultReader.readConfig();
		const categories = config?.categories ?? [
			"tasks", "decisions", "people", "projects", "lessons",
			"commitments", "inbox", "backlog",
		];

		const categoryColors: Record<string, string> = {
			tasks: "#e8a430",
			decisions: "#e85d4a",
			people: "#4a90e8",
			projects: "#4ae85d",
			lessons: "#9b59b6",
			commitments: "#e8a430",
			inbox: "#f39c12",
			backlog: "#95a5a6",
			patterns: "#2ecc71",
			goals: "#e67e22",
			research: "#3498db",
			agents: "#1abc9c",
			handoffs: "#e74c3c",
			templates: "#7f8c8d",
			preferences: "#9b59b6",
			transcripts: "#34495e",
		};

		const colorGroups = categories
			.filter((cat) => categoryColors[cat])
			.map((cat) => ({
				query: `path:${cat}/`,
				color: { a: 1, rgb: hexToRgbInt(categoryColors[cat] ?? "#7f8c8d") },
			}));

		const graphConfigPath = `${configDir}/graph.json`;
		let graphConfig: Record<string, unknown> = {};
		try {
			if (await adapter.exists(graphConfigPath)) {
				graphConfig = JSON.parse(await adapter.read(graphConfigPath)) as Record<string, unknown>;
			}
		} catch { /* fresh config */ }

		graphConfig["colorGroups"] = colorGroups;
		await adapter.write(graphConfigPath, JSON.stringify(graphConfig, null, 2));

		// 3. Enable the CSS snippet
		const appearancePath = `${configDir}/appearance.json`;
		let appearance: Record<string, unknown> = {};
		try {
			if (await adapter.exists(appearancePath)) {
				appearance = JSON.parse(await adapter.read(appearancePath)) as Record<string, unknown>;
			}
		} catch { /* fresh */ }

		const enabledSnippets = Array.isArray(appearance["enabledCssSnippets"])
			? (appearance["enabledCssSnippets"] as string[])
			: [];
		if (!enabledSnippets.includes("clawvault-graph")) {
			enabledSnippets.push("clawvault-graph");
		}
		appearance["enabledCssSnippets"] = enabledSnippets;
		await adapter.write(appearancePath, JSON.stringify(appearance, null, 2));

		new Notice("Graph colors configured (neural style). Reload Obsidian to see changes.");
	} catch (error) {
		new Notice(`ClawVault: Failed to setup graph colors: ${error instanceof Error ? error.message : "unknown"}`);
	}
}

function hexToRgbInt(hex: string): number {
	const cleaned = hex.replace("#", "");
	return parseInt(cleaned, 16);
}
